// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "hero": { "eyebrow": string; "title": string; "websiteButtonLabel": string; "websiteButtonUrl": string; "description": string; "formLabel": string; "buttonLabel": string; "confirmation": string; "finePrint": string }; "supporting": { "title": string; "description": string } } };
  export const home: { "hero": { "eyebrow": string; "title": string; "websiteButtonLabel": string; "websiteButtonUrl": string; "description": string; "formLabel": string; "buttonLabel": string; "confirmation": string; "finePrint": string }; "supporting": { "title": string; "description": string } };
}
